Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,36 +6,14 @@ on:
       - piyara2000-patch-2
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
-
-    - name: Install dependencies
-      run: npm install
-
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
-
-    - name: Run tests
-      run: npm test
-
   deploy:
     runs-on: ubuntu-latest
-    needs: test
 
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
 
-    - name: Deploy to EC2
+    - name: Run npm install
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.EC2_HOST }}
@@ -44,13 +22,36 @@ jobs:
         port: ${{ secrets.EC2_SSH_PORT }}
         script: |
           cd /home/ec2-user/TutorMeister/Controller
-          git pull origin main
-          npm install
+          /usr/bin/npm install
 
-          kill -9 $(lsof -t -i:5000) || true
+    - name: Run npm test
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USERNAME }}
+        key: ${{ secrets.EC2_PRIVATE_KEY }}
+        port: ${{ secrets.EC2_SSH_PORT }}
+        ignoreErrors: true
+        script: |
+          cd /home/ec2-user/TutorMeister/Controller
+          /usr/bin/npm test || true  # Capture exit code but continue regardless
 
-          npm start > /dev/null 2>&1 &
+    - name: Deploy changes
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_HOST }}
+        username: ${{ secrets.EC2_USERNAME }}
+        key: ${{ secrets.EC2_PRIVATE_KEY }}
+        port: ${{ secrets.EC2_SSH_PORT }}
+        script: |
+          cd /home/ec2-user/TutorMeister/Controller
+          /usr/bin/git pull origin main
+          /usr/bin/npm install
+
+          /bin/kill -9 $(/usr/sbin/lsof -t -i:5000) || true
+
+          /usr/bin/npm start > /dev/null 2>&1 &
           echo $! > deploy_pid
 
-          sleep 10
+          /bin/sleep 10
           exit 0
